# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-02 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0003_auto_20180701_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('00', 'CONFIRMED'), ('01', 'CANCELED'), ('10', 'COMPLETED')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('00', 'WAITING'), ('01', 'APPROVED'), ('10', 'REJECTED')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('00', 'APPROVED'), ('01', 'REJECTED'), ('10', 'CANCELED'), ('11', 'COMPLETED')], default='00', max_length=2),
        ),
    ]
