# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-02 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0004_auto_20180702_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='venue',
            field=models.CharField(default='Howrah', max_length=50),
            preserve_default=False,
        ),
    ]
