# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-03 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0005_freelancer_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.FloatField(blank=True, default=2.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.FloatField(blank=True, default=2.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='latitude',
            field=models.FloatField(blank=True, default=2.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='longitude',
            field=models.FloatField(blank=True, default=2.2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='credit_score',
            field=models.IntegerField(default=100),
        ),
    ]
