# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-05 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0007_auto_20180704_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='datetime',
        ),
        migrations.AddField(
            model_name='client',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('00', 'WAITING'), ('01', 'PLACED'), ('10', 'CANCELED'), ('11 ', 'COMPLETED')], default='00', max_length=2),
        ),
    ]
