# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-10 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0008_auto_20180705_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('00', 'WAITING'), ('01', 'PLACED'), ('10', 'CANCELED'), ('11', 'COMPLETED')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='ph_no',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
